"""LLM client -- Stage 20a Phase 5. Implements services/api/nodes/llm_interface.py's
LLMNodes protocol for two providers, selected by LLM_PROVIDER (.env.example documents
both):

  anthropic  -- Route A (ADR-009). The only provider whose output counts toward Stage
                20a's interim-assumption exit criteria.
  groq       -- dev-only substitute (user request, this session) for exercising the real
                call path while ANTHROPIC_API_KEY was being sorted. Defaults to a small/
                cheap model (GROQ_MODEL, default llama-3.1-8b-instant) to conserve
                tokens. Output from this provider is PROVISIONAL -- see .env.example's
                LLM_PROVIDER comment and ADR-009 SS"Model hosting route".

Both providers are prompted identically and parsed identically -- the only difference is
which SDK sends the request, which is the entire point of ADR-009's "one client interface"
guardrail: swapping providers is a constructor choice, not a prompt or parsing change.
"""
from __future__ import annotations

import json
import os

from pydantic import ValidationError

from packages.domain.evidence import Claim
from packages.domain.payloads import BatchPayload, PVPayload, SupplyPayload
from packages.domain.state import DecisionSupportOutput, GovernedState, ReasonCode

_BATCH_SYNTHESIZE_SYSTEM = """You are the Batch-Review decision-support agent for a GxP pharmaceutical batch reconciliation system.

Your ONLY job is to summarize the reconciliation findings factually, citing evidence_ids for every claim. You must NEVER recommend, suggest, or imply a release, rejection, reprocessing, relabeling, or recall decision -- that decision belongs exclusively to a human Qualified Person. Do not use words like "release", "reject", "approve for release", "recommend", or "cleared".

Respond with ONLY a JSON object matching this shape, no other text:
{"summary": "<factual summary>", "claims": [{"text": "<claim text>", "cites": ["<evidence_id>", ...]}]}

Every claim MUST cite at least one evidence_id from the evidence provided. Do not fabricate evidence_ids."""

_PV_SYNTHESIZE_SYSTEM = """You are the PV-Intake decision-support agent for a pharmacovigilance case-triage system.

Your ONLY job is to summarize the duplicate-check and terminology-normalization results factually, citing evidence_ids for every claim. You must NEVER state or imply a causality, seriousness, expectedness, or reportability determination -- those are final safety conclusions that belong exclusively to a human PV reviewer. Do not use words like "causality is", "seriousness is", "reportable", "not reportable", or "signal confirmed". You may only triage/prioritize and note the duplicate-suspicion status and normalization suggestions as reported by the tools.

Respond with ONLY a JSON object matching this shape, no other text:
{"summary": "<factual summary>", "claims": [{"text": "<claim text>", "cites": ["<evidence_id>", ...]}]}

Every claim MUST cite at least one evidence_id from the evidence provided. Do not fabricate evidence_ids."""

_SUPPLY_SYNTHESIZE_SYSTEM = """You are the Supply-Planning decision-support agent for a shortage/cold-chain planning system.

Your ONLY job is to rank and explain the candidate options already generated by the constraint filter, citing evidence_ids for every claim. You must NEVER state or imply an allocation, reservation, shipment authorization, or recall decision -- those are execution decisions that belong exclusively to a human Supply Chain VP and Quality co-approver. Do not use words like "allocate", "reserve for", "ship to", or "execute this option". You may only describe and compare the options as given.

Respond with ONLY a JSON object matching this shape, no other text:
{"summary": "<factual summary>", "claims": [{"text": "<claim text>", "cites": ["<evidence_id>", ...]}]}

Every claim MUST cite at least one evidence_id from the evidence provided. Do not fabricate evidence_ids."""

_BATCH_CRITIC_SYSTEM = """You are the Critic/Verifier for a GxP batch reconciliation decision-support system. You review a draft summary for citation quality ONLY -- you do not evaluate whether the batch should be released.

Check:
1. Does every claim have at least one citation? If not: MISSING_CITATION
2. Do all cited evidence_ids exist in the provided evidence list? If not: CITATION_UNRESOLVED
3. Does any claim assert something the cited evidence does not support? If so: CLAIM_EXCEEDS_EVIDENCE
4. Does the draft read as a disposition signal (release/reject/approve/recall recommendation)? If so: PROHIBITION_ADJACENT
5. Otherwise: approve.

Respond with ONLY a JSON object, no other text:
{"verdict": "approve_for_human" or "reject", "reason_code": null or one of "MISSING_CITATION"/"CITATION_UNRESOLVED"/"CLAIM_EXCEEDS_EVIDENCE"/"CONTRACT_VIOLATION"/"PROHIBITION_ADJACENT"}"""

_PV_CRITIC_SYSTEM = """You are the Critic/Verifier for a pharmacovigilance case-triage decision-support system. You review a draft summary for citation quality ONLY -- you do not make a safety determination.

Check:
1. Does every claim have at least one citation? If not: MISSING_CITATION
2. Do all cited evidence_ids exist in the provided evidence list? If not: CITATION_UNRESOLVED
3. Does any claim assert something the cited evidence does not support? If so: CLAIM_EXCEEDS_EVIDENCE
4. Does the draft read as a causality/seriousness/expectedness/reportability/signal determination? If so: PROHIBITION_ADJACENT
5. Otherwise: approve.

Respond with ONLY a JSON object, no other text:
{"verdict": "approve_for_human" or "reject", "reason_code": null or one of "MISSING_CITATION"/"CITATION_UNRESOLVED"/"CLAIM_EXCEEDS_EVIDENCE"/"CONTRACT_VIOLATION"/"PROHIBITION_ADJACENT"}"""

_SUPPLY_CRITIC_SYSTEM = """You are the Critic/Verifier for a supply-planning decision-support system. You review a draft summary for citation quality ONLY -- you do not authorize execution.

Check:
1. Does every claim have at least one citation? If not: MISSING_CITATION
2. Do all cited evidence_ids exist in the provided evidence list? If not: CITATION_UNRESOLVED
3. Does any claim assert something the cited evidence does not support? If so: CLAIM_EXCEEDS_EVIDENCE
4. Does the draft read as an allocation/reservation/shipment/execution authorization? If so: PROHIBITION_ADJACENT
5. Otherwise: approve.

Respond with ONLY a JSON object, no other text:
{"verdict": "approve_for_human" or "reject", "reason_code": null or one of "MISSING_CITATION"/"CITATION_UNRESOLVED"/"CLAIM_EXCEEDS_EVIDENCE"/"CONTRACT_VIOLATION"/"PROHIBITION_ADJACENT"}"""

_SYNTHESIZE_SYSTEMS = {
    "batch_review": _BATCH_SYNTHESIZE_SYSTEM, "pv_intake": _PV_SYNTHESIZE_SYSTEM, "supply_planning": _SUPPLY_SYNTHESIZE_SYSTEM,
}
_CRITIC_SYSTEMS = {
    "batch_review": _BATCH_CRITIC_SYSTEM, "pv_intake": _PV_CRITIC_SYSTEM, "supply_planning": _SUPPLY_CRITIC_SYSTEM,
}


def _build_synthesize_user_prompt(state: GovernedState) -> str:
    payload = state["domain_payload"]
    evidence = [{"evidence_id": e.evidence_id, "status": e.status, "source": e.source} for e in state["evidence"]]

    if isinstance(payload, BatchPayload):
        findings = [f.model_dump() for f in payload.findings]
        body = {"batch_id": payload.batch_id, "findings": findings}
    elif isinstance(payload, PVPayload):
        body = {
            "case_id": payload.case_id, "duplicate_suspected": payload.duplicate_suspected,
            "candidates": [c.model_dump() for c in payload.candidates],
            "normalization_suggestions": [s.model_dump() for s in payload.normalization_suggestions],
        }
    elif isinstance(payload, SupplyPayload):
        body = {"product_id": payload.product_id, "options": [o.model_dump() for o in payload.options]}
    else:
        raise TypeError(f"_build_synthesize_user_prompt: unrecognized payload type {type(payload)!r}")

    body["available_evidence"] = evidence
    return json.dumps(body)


def _build_critic_user_prompt(state: GovernedState) -> str:
    draft = state["draft_output"]
    evidence_ids = [e.evidence_id for e in state["evidence"]]
    return json.dumps({"draft": draft.model_dump(), "available_evidence_ids": evidence_ids})


def _parse_synthesize_response(text: str) -> DecisionSupportOutput:
    data = json.loads(text.strip().removeprefix("```json").removesuffix("```").strip())
    claims = tuple(Claim(text=c["text"], cites=tuple(c.get("cites", []))) for c in data["claims"])
    return DecisionSupportOutput(summary=data["summary"], claims=claims)


def _parse_critic_response(text: str) -> tuple[str, ReasonCode | None]:
    data = json.loads(text.strip().removeprefix("```json").removesuffix("```").strip())
    verdict = data["verdict"]
    reason_code = ReasonCode(data["reason_code"]) if data.get("reason_code") else None
    if verdict not in ("approve_for_human", "reject"):
        raise ValueError(f"Unrecognized verdict {verdict!r}")
    if verdict == "reject" and reason_code is None:
        # A model that rejects without a reason code violates the critic's own output
        # contract (every reject must carry a reason -- failure_and_loop_guards.md SS4's
        # "no blind retry" rule assumes this). Found live under Groq this session:
        # route_after_critic's routing logic assumes >=1 code exists once verdict != approve
        # -- without this, codes[-1] crashes with IndexError on a genuinely malformed but
        # not-exception-raising response. Treat as the model's own contract violation.
        raise ValueError("verdict='reject' with no reason_code -- critic output contract violation")
    return verdict, reason_code


class AnthropicLLM:
    """Route A (ADR-009). Direct Anthropic API in dev/20a; Azure AI Foundry is the
    deployment-time binding behind this same interface (ADR-009 SS"Azure is the
    DEPLOYMENT target")."""

    def __init__(self, model: str | None = None):
        import anthropic

        self._client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
        self._model = model or os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-5")

    def _call(self, system: str, user: str) -> tuple[str, int, int]:
        resp = self._client.messages.create(
            model=self._model, max_tokens=1024, system=system,
            messages=[{"role": "user", "content": user}],
        )
        return resp.content[0].text, resp.usage.input_tokens, resp.usage.output_tokens

    def synthesize(self, state: GovernedState) -> tuple[DecisionSupportOutput, int, int]:
        text, tin, tout = self._call(_SYNTHESIZE_SYSTEMS[state["workflow"]], _build_synthesize_user_prompt(state))
        try:
            return _parse_synthesize_response(text), tin, tout
        except (json.JSONDecodeError, KeyError, ValidationError):
            return DecisionSupportOutput(summary="[PARSE_ERROR]", claims=()), tin, tout

    def critic(self, state: GovernedState) -> tuple[str, ReasonCode | None, int, int]:
        text, tin, tout = self._call(_CRITIC_SYSTEMS[state["workflow"]], _build_critic_user_prompt(state))
        try:
            verdict, reason_code = _parse_critic_response(text)
        except (json.JSONDecodeError, KeyError, ValueError):
            verdict, reason_code = "reject", ReasonCode.CONTRACT_VIOLATION
        return verdict, reason_code, tin, tout


class GroqLLM:
    """Dev-only, provisional (see module docstring). OpenAI-compatible API -- reuses the
    `openai` SDK with Groq's base_url, no new dependency."""

    def __init__(self, model: str | None = None):
        import openai

        self._client = openai.OpenAI(api_key=os.environ["GROQ_API_KEY"], base_url="https://api.groq.com/openai/v1")
        self._model = model or os.environ.get("GROQ_MODEL", "llama-3.1-8b-instant")

    def _call(self, system: str, user: str) -> tuple[str, int, int]:
        resp = self._client.chat.completions.create(
            model=self._model,
            messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
        )
        text = resp.choices[0].message.content
        usage = resp.usage
        return text, usage.prompt_tokens, usage.completion_tokens

    def synthesize(self, state: GovernedState) -> tuple[DecisionSupportOutput, int, int]:
        text, tin, tout = self._call(_SYNTHESIZE_SYSTEMS[state["workflow"]], _build_synthesize_user_prompt(state))
        try:
            return _parse_synthesize_response(text), tin, tout
        except (json.JSONDecodeError, KeyError, ValidationError):
            return DecisionSupportOutput(summary="[PARSE_ERROR]", claims=()), tin, tout

    def critic(self, state: GovernedState) -> tuple[str, ReasonCode | None, int, int]:
        text, tin, tout = self._call(_CRITIC_SYSTEMS[state["workflow"]], _build_critic_user_prompt(state))
        try:
            verdict, reason_code = _parse_critic_response(text)
        except (json.JSONDecodeError, KeyError, ValueError):
            verdict, reason_code = "reject", ReasonCode.CONTRACT_VIOLATION
        return verdict, reason_code, tin, tout


def get_llm():
    """Provider selected by LLM_PROVIDER (.env.example). Raises KeyError with a clear
    message if the corresponding API key is absent -- callers should catch this the same
    way Phase 4's stub-vs-live test split treats a missing key: skip, don't fail."""
    provider = os.environ.get("LLM_PROVIDER", "anthropic")
    if provider == "anthropic":
        return AnthropicLLM()
    if provider == "groq":
        return GroqLLM()
    raise ValueError(f"Unknown LLM_PROVIDER {provider!r} -- expected 'anthropic' or 'groq'.")
